name: flutter_localization
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # Localisation e Internationalisation
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  #State managment Library
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0

  #Store user data
  flutter_secure_storage: ^3.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/locale/
